accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.login_account, name="login_account"),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_thanks/$', views.register_thanks, name='register_thanks'),
    url(r'^logout/$', views.logout_account, name='logout_account'),
    url(r'^recover_password/$', views.recover_password, name='recover_password'),
    url(r'^password_reset', PasswordResetView.as_view(), {
        'template_name':'password_reset_form.html', 
        'email_template_name':'password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', PasswordResetDoneView.as_view(), {'template_name':'registration/password_reset_done.html'}, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),  {'template_name':'accounts/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^reset/done', PasswordResetCompleteView.as_view(), {'template_name':'registration/password_reset_complete.html'}, name="password_reset_complete"),
]

misPerris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('web.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url('^', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'contacto', views.contacto, name='contacto'),
    path(r'lista_perros/', views.lista_perros, name='lista_perros'),
    path(r'agregar_perro/', views.agregar_perro, name='agregar_perro'),
    url(r'^(?P<id>\d+)/editar/$', views.editar_perro, name="editar_perro"),
    url(r'^(?P<id>\d+)/adoptar/$', views.adoptar_perro, name="adoptar_perro"),
    path(r'<id>/eliminar/', views.eliminar_perro, name='eliminar_perro'),
]

accounts/models.py
from django.db import models

# Create your models here.

web/models.py
from django.db import models
from django.urls import reverse
from cloudinary.models import CloudinaryField

class Estado(models.Model):
    descripcion = models.CharField(max_length=30)

    def __str__(self):
        return self.descripcion

class Perro(models.Model):
    nombre = models.CharField(max_length=100)
    foto = models.ImageField(default='default.png', blank=True)
    raza = models.CharField(default='Quiltro', max_length=100)
    descripcion = models.TextField()
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, default=1)
    dueno = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.nombre

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Requerido')
    last_name = forms.CharField(max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(max_length=254, help_text='Requerido')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label = "Nombres"
        self.fields['last_name'].label = "Apellidos"

web/forms.py
from django import forms
from . import models

class AgregarPerro(forms.ModelForm):
    class Meta:
        model = models.Perro
        fields = ['nombre','raza','descripcion','dueno','estado','foto']

class ModificarPerro(forms.ModelForm):
    class Meta:
        model = models.Perro
        fields = ['nombre','raza','descripcion','foto', 'estado', 'dueno']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import SignUpForm

# Create your views here.

def register(request):
    if request.method == 'POST': #validamos que se haya submiteado algo
        form = SignUpForm(request.POST) # Se crea instancia del formulario con la informacion de POST
        if form.is_valid(): # validamos formulario
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:register_thanks')
    else:
        form = SignUpForm() # Se crea instancia vacia del formulario
    return render(request, 'accounts/register.html', {'form':form})

def login_account(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Se inicia sesion
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('web:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_account(request):
    if request.method == 'POST':
        logout(request)
        return redirect('web:home')

def recover_password(request):
    return render(request, 'accounts/recuperar_pass.html')

def register_thanks(request):
    return render(request, 'accounts/register_thanks.html')

web/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from . import forms
from .models import Perro
from .models import Estado
from .forms import ModificarPerro

# Create your views here.

def list_perros(request):
    return render(request, 'web/list_perros.html', {})

def add_perro(request):
    return render(request, 'web/add_perro.html', {})

def home (request):
    return render(request, 'home.html')

def contacto (request):
    return render(request, 'contacto.html')

def registro_perros(request):
    return render(request, 'web/registro_perros.html')

def lista_perros(request):
    if request.method == 'POST':
        filtro = request.POST.get('filtro')
        perros = Perro.objects.filter(estado__pk=filtro)
    else:
        perros = Perro.objects.all().order_by('nombre')
    
    adoptado = get_object_or_404(Estado, pk=1)
    disponible = get_object_or_404(Estado, pk=2)

    return render(request, 'lista_perros.html', {'perros' : perros, 'adoptado':adoptado, 'disponible':disponible})

@login_required(login_url="/accounts/login/")
def agregar_perro(request):
    if request.method == 'POST':
        form = forms.AgregarPerro(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('web:agregar_perro')
    else:
        form = forms.AgregarPerro()
    return render(request, 'agregar_perro.html', {'form':form})

@login_required(login_url="/accounts/login/")
def editar_perro(request, id=None):
    instance = get_object_or_404(Perro, id=id)
    form = ModificarPerro(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('web:lista_perros')
    context = {
        "nombre":instance.nombre,
        "instance":instance,
        "form":form,
    }
    return render(request, 'editar_perro.html', context)

@login_required(login_url="/accounts/login/")
def adoptar_perro(request, id=None):
    estado = get_object_or_404(Estado, pk=1)
    perro = get_object_or_404(Perro, id=id)
    perro.estado = estado
    perro.dueno = request.user
    perro.save(update_fields=["estado"])
    perro.save(update_fields=["dueno"])
    return redirect('web:lista_perros')


@login_required(login_url="/accounts/login/")
def eliminar_perro(request, id=None):
    instance = get_object_or_404(Perro, id=id)
    instance.delete()
    return redirect('web:lista_perros')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Iniciar Sesión</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            <form action="{% url 'accounts:login_account' %}" method="POST" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Iniciar Sesión <i class="fa fa-chevron-right"></i></button>
                <a href="{% url 'accounts:password_reset' %}" class="mt-3">Recuperar contraseña</a>
            </form>
        </div>
    </div>

</section>

{% endblock %}

accounts/templates/accounts/recover_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Recuperar Contraseña</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            <form action="{% url 'accounts:recover' %}" method="POST" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Recuperar contraseña <i class="fa fa-chevron-right"></i></button>
            </form>
        </div>
    </div>

</section>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Registrarme</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            <form action="{% url 'accounts:register' %}" method="POST" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Registrarme <i class="fa fa-chevron-right"></i></button>
                <a href="{% url 'accounts:login_account' %}" class="mt-3">¿Ya tienes una cuenta? Inicia sesión</a>
            </form>
        </div>
    </div>

</section>

{% endblock %}

accounts/templates/accounts/register_thanks.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Registro exitoso</h2>
                </div>
            </div>
        </div>
    </section>
</div>
<section class="container">
    <div class="row">
        <div class="col-12 m-4">
            <div class="jumbotron">
                <h1 class="display-4">¡Bienvenido, {{user.username}}!</h1>
                <p class="lead">Tu registro ha sido exitoso, desde ahora podrás iniciar sesión.</p>
                <hr class="my-4">
                <a class="btn btn-primary btn-lg" href="/" role="button">Ir a Inicio</a>
            </div>
        </div>
    </div>

</section>

{% endblock %}

web/templates/agregar_perro.html
{% extends 'base.html' %}

{% block content %}
<!-- <form action="{% url 'web:lista_perros' %}" method="POST" class="form-filtro row">
        {% csrf_token %}
        <select name="filtro" class="col-xs-6">
            <option value="0" selected disabled>Seleccione Estado</option>
            <option value="1">Adoptado</option>
            <option value="2">Disponible</option>
            <option value="3">Rescatado</option>

        </select>
        <input type="submit" value="Filtrar" class="col-xs-6">
    </form> -->

<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
            ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Agregar Perro</h2>
                </div>
            </div>
        </div>
    </section>
</div>

<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            <form action="" method="POST" enctype="multipart/form-data" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Agregar <i class="fa fa-chevron-right"></i></button>
            </form>
        </div>
    </div>

</section>

{% endblock %}

web/templates/base.html
{% load static %}
<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Fundación Mis Perris">
    <meta name="author" content="Texia Gonzalez - Sebastian Becerra">
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="theme-color" content="#ffffff">
    <title>Mis Perris</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/{% static '' %}/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/{% static '' %}/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/{% static '' %}/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static '/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static '/{% static '' %}/images/safari-pinned-tab.svg' %}" color="#5bbad5">
    <!-- CDN FontAwesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <!-- CDN Fancybox core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.4.1/jquery.fancybox.min.css" />
    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static '/css/main.css' %}" rel="stylesheet">
</head>

<body class="home">
    <!-- Header
        ================================================== -->
    <header>
        <nav class="top-bar navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            {% if user.is_authenticated %}
            <span class="text-white">Bienvenido, {{user.username}}</span>
            {% endif %}
            <ul class="navbar-nav ml-auto list-inline">
                {% if user.is_authenticated %}
                <li class="nav-item list-inline-item">
                    <form class='logout' action="{% url 'accounts:logout_account' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link">Cerrar Sesión</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item list-inline-item"> <a class="nav-link" href="{% url 'accounts:login_account' %}">Iniciar
                        Sesión</a>
                </li>
                <li class="nav-item list-inline-item"> <a class="nav-link" href="{% url 'accounts:register' %}">Registro</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-theme menu">
            <a class="navbar-brand" href="/"><img alt="" src="{% static '' %}/images/logo.png" class="w-100 logo" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu-mobile"
                aria-controls="menu-mobile" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="menu-mobile">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if request.path == '/' %} active {% endif %}"> <a class="nav-link" href="/">Inicio</a>
                    </li>
                    <li class="nav-item"> <a class="nav-link" href="#about-us">Quienes Somos</a> </li>
                    <li class="nav-item"> <a class="nav-link" href="#">Servicios</a> </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item {% if request.path == '/lista_perros/' %} active {% endif %}"> <a class="nav-link"
                            href="{% url 'web:lista_perros' %}">Adoptar</a> </li>
                    {% endif %}
                    <li class="nav-item {% if request.path == '/contacto' %} active {% endif %}"> <a class="nav-link"
                            href="{% url 'web:contacto' %}">Contáctanos</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <!-- Footer
        ================================================== -->
    <footer class="bg-light">
        <div class="container">
            <p class="float-right"><a href="#">Ir arriba</a></p>
            <p>&copy; <span class="js-year">----</span> - Fundación Mis Perris</p>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.4.1/jquery.fancybox.min.js"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
</body>

</html>

web/templates/contacto.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content contacto">
    <!-- Slider
        ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Contáctanos</h2>
                </div>
            </div>
        </div>
    </section>
    <section id="#contact-us" class="about-us">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Formulario de Contacto</h2>
                    <form class="mt-4">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="nombre">Nombre</label>
                                <input type="text" class="form-control" id="nombre" placeholder="Ej: Juan Ramírez"
                                    required> </div>
                            <div class="form-group col-md-6">
                                <label for="run">RUN</label>
                                <input type="text" class="form-control" id="run" maxlength="12" placeholder="Ej: 11.111.111-1"
                                    required> </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="email">Correo Electrónico</label>
                                <input type="email" class="form-control" id="email" placeholder="Ej: correo@correo.cl"
                                    required> </div>
                            <div class="form-group col-md-4">
                                <label for="email">Fecha de Nacimiento</label>
                                <input autocomplete="off" type="text" class="form-control" id="fechaNac" placeholder="Ej: 17-08-1998"
                                    required data-toggle="datepicker"> </div>
                            <div class="form-group col-md-4">
                                <label for="email">Teléfono de Contacto</label>
                                <input type="number" class="form-control" id="telefono" placeholder="Ej: +56 9 4264 9933"
                                    required> </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="regiones">Región</label>
                                <select class="form-control" id="regiones">
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="comunas">Ciudad</label>
                                <select class="form-control" id="comunas">
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="tipo-vivienda">Tipo de Vivienda</label>
                                <select class="form-control" id="tipo-vivienda">
                                    <option selected disabled>Selecciona tu tipo de vivienda...</option>
                                    <option value="casa-patio-grande">Casa con patio grande</option>
                                    <option value="casa-patio-pequeno">Casa con patio pequeño</option>
                                    <option value="casa-sin-patio">Casa sin patio</option>
                                    <option value="departamento">Departamento</option>
                                </select>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block btn-lg">Enviar</button>
                    </form>
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>
    </section>
    <!-- /.container -->
</div>
{% endblock %}

web/templates/editar_perro.html
{% extends 'base.html' %}

{% block content %}
<!-- <form action="{% url 'web:lista_perros' %}" method="POST" class="form-filtro row">
        {% csrf_token %}
        <select name="filtro" class="col-xs-6">
            <option value="0" selected disabled>Seleccione Estado</option>
            <option value="1">Adoptado</option>
            <option value="2">Disponible</option>
            <option value="3">Rescatado</option>

        </select>
        <input type="submit" value="Filtrar" class="col-xs-6">
    </form> -->

<!-- INICIAR SESION -->
<div class="content login">
    <!-- Slider
            ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Modificar Perro</h2>
                </div>
            </div>
        </div>
    </section>
</div>

<section class="container">
    <div class="row">
        <div class="col-12 col-sm-6 m-auto">
            {% if perms.perro.change_perro %}
            <form action="" method="POST" enctype="multipart/form-data" class="bg-light card form-accounts p-4 m-4">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <button class="btn btn-primary btn-block mt-3" type="submit">Modificar <i class="fa fa-chevron-right"></i></button>
            </form>
            {% else %}
            <div class="col-12 mb-4">
                <ul class="errorlist">
                    <li>Acceso Denegado: Debes ser administrador para Agregar Perritos.</li>
                </ul>
            </div>
            {% endif %}
        </div>
    </div>

</section>

{% endblock %}

web/templates/lista_perros.html
{% extends 'base.html' %}

{% block content %}

<div class="content lista_perros">
    <!-- Slider
    ================================================== -->
    <section class="page-title bg-theme">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center text-white">
                    <h2>Nuestros Perris</h2>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button"
                    aria-expanded="false" aria-controls="multiCollapseExample1"><i class="fa fa-plus"></i> Opciones</a>
            </div>
            <div class="col-12 mt-4">
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                    <div class="card card-body">
                        <form action="{% url 'web:lista_perros' %}" method="POST" class="form-inline">
                            {% csrf_token %}
                            <div class="form-group col-4">
                                <select name="filtro" class="custom-select w-100">
                                    <option value="0" selected disabled>Seleccione Estado</option>
                                    <option value="1">Adoptado</option>
                                    <option value="2">Disponible</option>
                                    <option value="3">Rescatado</option>
                                </select>
                            </div>
                            <div class="form-group col-2">
                                <input type="submit" value="Filtrar" class="btn btn-primary btn-block">
                            </div>
                            {% if perms.perro.change_perro %}
                            <div class="form-group col-2">
                                <a href="{% url 'web:agregar_perro' %}" class="btn btn-success btn-block">Agregar
                                    Perro</a>
                            </div>
                            {% endif %}

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            {% for perro in perros %}
            <div class="col-12 col-sm-6 col-lg-4">
                <div class="card mb-4">
                    <img class="card-img-top" src="{{ perro.foto.url }}" alt="{{ perro.nombre }}">
                    <div class="card-body">
                        <h3 class="card-title">{{ perro.nombre }}</h3>
                        <h5 class="card-title">{{ perro.raza}}</h5>
                        <p class="card-text">{{ perro.descripcion }}</p>
                        {% if perro.estado == adoptado %}
                        <h6 class="">Adoptado por {{ perro.dueno }}</h6>
                        {% endif %}
                    </div>
                    <div class="card-footer">
                        {% if perms.perro.change_perro %}
                        <a href="{% url 'web:editar_perro' id=perro.id %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'web:eliminar_perro' id=perro.id %}" class="btn btn-danger">Eliminar</a>
                        {% endif %}
                        {% if perro.estado == disponible %}
                        <a href="{% url 'web:adoptar_perro' id=perro.id %}" class="btn btn-success">Adoptar</a>
                        {% endif %}
                    </div>
                </div>

            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}